
###
GET http://localhost:3000/test

###

GET http://localhost:3000/jobs

###




### from earlier examples

POST http://localhost:3000/searchbycategory
content-type: application/json

{"jobCategory":"Accounting"}

###
GET http://localhost:3000

###

POST https://erin-eager-indri.cyclic.app/searchbycategory
content-type: application/json

{"jobCategory":"Sales"}